### ISSUE TITLE
Plugin Fails to Download Covers

### ISSUE THREAD

**Issue by plumpro** [lbschenkel/calibre-amazon-hires-covers#2]
Recently the plugin has stopped working. It fails every time.

> ****************************** Kindle hi-res covers Covers ****************************** 
> Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0')] 
> Failed to download valid cover 
> Took 3.5918891429901123 seconds 
> ASIN present in metadata: B0CD2D66FH
> Cover URLs: ['http://z2-ec2.images-amazon.com/images/P/B0CD2D66FH.01.MAIN._SCRM_.jpg', 'https://s3.cn-north-1.amazonaws.com.cn/sitbweb-cn/content/B0CD2D66FH/images/cover.jpg']
> Create link to download cover
> Downloading 2 covers 
> 
> ********************************************************************************

**Comment by lbschenkel** [comment]
Thanks. Fixed in 0.5.1.
